class Mime

  @@mime_map = {
    "aac"=>"audio/aac",
    "abw"=>"application/x-abiword",
    "apng"=>"image/apng",
    "arc"=>"application/x-freearc",
    "avif"=>"image/avif",
    "avi"=>"video/x-msvideo",
    "azw"=>"application/vnd",
    "bin"=>"application/octet-stream",
    "bmp"=>"image/bmp",
    "bz"=>"application/x-bzip",
    "bz2"=>"application/x-bzip2",
    "cda"=>"application/x-cdf",
    "csh"=>"application/x-csh",
    "css"=>"text/css",
    "csv"=>"text/csv",
    "doc"=>"application/msword",
    "docx"=>"application/vnd",
    "eot"=>"application/vnd",
    "epub"=>"application/epub+zip",
    "gz"=>["application/gzip", "Windows and macOS upload"],
    "gif"=>"image/gif",
    "htm"=>"text/html",
    "html"=>"text/html",
    "ico"=>"image/vnd",
    "ics"=>"text/calendar",
    "jar"=>"application/java-archive",
    "jpeg"=>"image/jpeg",
    "jpg"=>"image/jpeg",
    "js"=>"text/javascript (Specifications: HTML and RFC 9239)",
    "json"=>"application/json",
    "jsonld"=>"application/ld+json",
    "md"=>"text/markdown",
    "mid"=>["audio/midi", "audio/x-midi"],
    "midi"=>["audio/midi", "audio/x-midi"],
    "mjs"=>"text/javascript",
    "mp3"=>"audio/mpeg",
    "mp4"=>"video/mp4",
    "mpeg"=>"video/mpeg",
    "mpkg"=>"application/vnd",
    "odp"=>"application/vnd",
    "ods"=>"application/vnd",
    "odt"=>"application/vnd",
    "oga"=>"audio/ogg",
    "ogv"=>"video/ogg",
    "ogx"=>"application/ogg",
    "opus"=>"audio/ogg",
    "otf"=>"font/otf",
    "png"=>"image/png",
    "pdf"=>"application/pdf",
    "php"=>"application/x-httpd-php",
    "ppt"=>"application/vnd",
    "pptx"=>"application/vnd",
    "rar"=>"application/vnd",
    "rtf"=>"application/rtf",
    "sh"=>"application/x-sh",
    "svg"=>"image/svg+xml",
    "tar"=>"application/x-tar",
    "tif"=>"image/tiff",
    "tiff"=>"image/tiff",
    "ts"=>"video/mp2t",
    "ttf"=>"font/ttf",
    "txt"=>"text/plain",
    "vsd"=>"application/vnd",
    "wav"=>"audio/wav",
    "weba"=>"audio/webm",
    "webm"=>"video/webm",
    "webmanifest"=>"application/manifest+json",
    "webp"=>"image/webp",
    "woff"=>"font/woff",
    "woff2"=>"font/woff2",
    "xhtml"=>"application/xhtml+xml",
    "xls"=>"application/vnd",
    "xlsx"=>"application/vnd",
    "xml"=>["application/xml is recommended as of RFC 7303 (section 4",
    "but text/xml is still used sometimes", "an Atom feed is application/atom+xml",
    "but application/xml serves as a valid default"],
    "xul"=>"application/vnd",
    "zip"=>["application/zip", "Windows uploads"],
    "3gp"=>"video/3gpp; audio/3gpp if it doesn't contain video",
    "3g2"=>"video/3gpp2; audio/3gpp2 if it doesn't contain video",
    "7z"=>"application/x-7z-compressed"
  }

  def self.mimer(type)
    @@mime_map[type]
  end
end